name: Build Guide

on:
  workflow_dispatch:

jobs:
  build-guide:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11']
    env:
      JDK_VERSION:  ${{ matrix.java }}
      GIT_NAME: ${{ github.actor }}
      GIT_EMAIL: assarn@objectcomputing.com
      GUIDE_BRANCH: ${{ github.ref }}
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cash Gradle Artifacts
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Checkout Working Guide
        uses: actions/checkout@v2
      - name: Invoke Check and PublishGuide Tasks
        run: ./check-and-publishGuide-download.sh
      - name: Checkout grails-guide-repo
        uses: actions/checkout@v2
        with:
          repository: grails/grails-guides
          token: ${{ secrets.MY_PAT }}
          ref: gh-pages
          path: gh-pages
      - name: Push Guide to gh-pages
        run: |
          echo "**************** ls after the second checkout *********"
          ls -al
          echo "**************** cd gh-pages then ls *********"
          ls -al gh-pages

