# This is a basic workflow that is manually triggered

name: Build Guide

on:
  workflow_dispatch:

jobs:
  build-guide:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke build-gradle script
      run: pwd
    - name: another
      run: cd ..
    - name: another
      run: ls -al
