name: Build Guide

on:
  workflow_dispatch:

jobs:
  build-guide:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11']
    env:
      JDK_VERSION:  ${{ matrix.java }}
      GIT_NAME: ${{ github.actor }}
      GIT_EMAIL: assarn@objectcomputing.com
      GUIDE_BRANCH: ${{ github.ref }}
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cash Gradle Artifacts
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Checkout Working Guide
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Invoke build-gradle script
        run: ./check-and-publishGuide-tasks.sh
