name: Build Guide

on:
  workflow_dispatch:

jobs:
  build-guide:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11']
    env:
      JDK_VERSION:  ${{ matrix.java }}
      GIT_NAME: ${{ github.actor }}
      GUIDE_BRANCH: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Invoke build-gradle script
        run: ./actions-build-guide.sh
