name: Build Guide

on:
  workflow_dispatch:

jobs:
  build-guide:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11']
    env:
      JDK_VERSION:  ${{ matrix.java }}
      GIT_NAME: ${{ github.actor }}
      GIT_EMAIL: assarn@objectcomputing.com
      GH_TOKEN: ${{ github.token }}
      GUIDE_BRANCH: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Invoke build-gradle script
#        uses: oleksiyrudenko/gha-git-credentials@v2.1
#        with:
#          global: true
#          name: ${{ github.actor }}
#          email: assarn@objectcomputing.com
#          actor: ${{ github.actor }}
#          token: ${{ github.token }}
        run: ./actions-build-guide.sh
