name: Github Push
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GIT_NAME: ${{ github.actor }}
      GIT_EMAIL: assarn@objectcomputing.com
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: niravassar/dummy-repo
          token: ${{ secrets.MY_PAT }}
      - name: Try Commit
        run: |
          echo "insert text here" > myautofile.txt
          cat myautofile.txt
          ls -al
          echo "******** committing the file *********"
          git config --local user.email "${{ env.GIT_EMAIL }}"
          git config --local user.name "${{ env.GIT_NAME }}"
          git add .
          git commit -a -m "adding the myautofile.txt"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          repository: niravassar/dummy-repo

