# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:

jobs:
  build-guide:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
