name: Publish Guide
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GIT_NAME: ${{ github.actor }}
      GIT_EMAIL: assarn@objectcomputing.com
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: niravassar/dummy-repo
          token: ${{ secrets.GITHUB_TOKEN }}
          path: dummy-repo
      - name: Try Commit
        run: |
          echo "******* ls **********"
          cd dummy-repo
          echo "******* create new file **********"
          echo "insert text here" > myautofile.txt
          echo "******* cat myfile **********"
          cat myautofile.txt
          echo "******* ls files **********"
          ls -al
          echo $GITHUB_REF
          echo "******** committing the file *********"
          git config --global user.name "${{ env.GIT_NAME }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"
          git add .
          git commit -a -m "adding the myautofile.txt"
          echo "******** name and email *********"
          echo "${{ github.actor }} --- "${{ env.GIT_EMAIL }}""
          git push --force --quiet "https://${{ env.GIT_NAME }}:${{ secrets.GITHUB_TOKEN }}@github.com/niravassar/dummy-repo" master:master
