name: Publish Guide
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: grails/grails-guides
          token: ${{ secrets.GITHUB_TOKEN }} # `GitHub_PAT` is a secret that contains your PAT
          path:
      - name: Try Commit
        run: |
          echo "******* ls **********"
          git checkout -b gh-pages
          cd gh-pages
          ls -al
