name: Publish Guide
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: grails/grails-guides
          token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret that contains your PAT
          path: gh-pages
      - name: Try Commit
        run: |
          echo "******* ls **********"
          ls -al
