name: Publish Guide
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GIT_NAME: ${{ github.actor }}
      GIT_EMAIL: assarn@objectcomputing.com
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: niravassar/dummy-repo
          token: ${{ secrets.GITHUB_TOKEN }} # `GitHub_PAT` is a secret that contains your PAT
          path: dummy-repo
      - name: Try Commit
        run: |
          echo "******* ls **********"
          cd dummy-repo
          echo "******* create new file **********"
          echo "insert text here" > myautofile.txt
          echo "******* cat myfile **********"
          cat myautofile.txt
          echo "******* ls files **********"
          ls -al
          echo $GITHUB_REF
          echo "******** committing the file *********"
          git config --global user.name "$GIT_NAME"
          git config --global user.email "$GIT_EMAIL"
          git add .
          git commit -a -m "adding the myautofile.txt"
          git push https://$USERNAME:$REPO_KEY@github.com/niravassar/dummy-repo.git HEAD
        env:
          REPO_KEY: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.actor }}
