name: Publish Guide
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GIT_NAME: ${{ github.actor }}
      GIT_EMAIL: assarn@objectcomputing.com
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          #repository: niravassar/dummy-repo
          token: ${{ secrets.GITHUB_TOKEN }}
          path: dummy-repo
      - name: Try Commit
        run: |
          cd dummy-repo
          echo "insert text here" >> myautofile.txt
          cat myautofile.txt
          ls -al
          echo "******** committing the file *********"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "${{ env.GIT_EMAIL }}"
          git add .
          git commit -a -m "adding the myautofile.txt"
          git push
