name: Setup Git credentials
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GIT_NAME: ${{ github.actor }}
      GIT_EMAIL: assarn@objectcomputing.com
    steps:
      - name: Checkout private tools
        uses: actions/checkout@master
        with:
          repository: niravassar/dummy-repo
          token: ${{ secrets.GITHUB_TOKEN }}
          path: dummy-repo
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Try Commit
        run: |
          cd dummy-repo
          echo "insert text here" >> myautofile.txt
          cat myautofile.txt
          ls -al
          echo "******** committing the file *********"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "${{ env.GIT_EMAIL }}"
          git add .
          git commit -a -m "adding the myautofile.txt"
          git push
